# Generated by Django 5.1.7 on 2025-06-24 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('initials', models.CharField(max_length=10, unique=True)),
                ('grade', models.CharField(max_length=10)),
                ('has_voted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Aspirant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=10)),
                ('photo', models.ImageField(default='aspirants/placeholder.jpg', upload_to='aspirants/')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.position')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspirant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.aspirant')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.learner')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.position')),
            ],
            options={
                'unique_together': {('learner', 'position')},
            },
        ),
    ]
