# Generated by Django 5.1.7 on 2025-06-24 16:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_alter_learner_grade_alter_learner_initials'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='vote',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vote',
            name='aspirant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='election.aspirant'),
        ),
    ]
