# Generated by Django 5.1.7 on 2025-06-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_alter_vote_unique_together_vote_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='initials',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='learner',
            unique_together={('initials', 'grade')},
        ),
    ]
