# Generated by Django 5.1.7 on 2025-06-27 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0004_alter_learner_initials_alter_learner_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aspirant',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='aspirant',
            name='name',
        ),
        migrations.AddField(
            model_name='aspirant',
            name='learner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='election.learner'),
        ),
    ]
