# Generated by Django 5.1.7 on 2025-06-27 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0005_remove_aspirant_grade_remove_aspirant_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirant',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.learner'),
        ),
    ]
