# Generated by Django 5.1.7 on 2025-06-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0006_alter_aspirant_learner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aspirant',
            name='learner',
        ),
        migrations.AddField(
            model_name='aspirant',
            name='grade',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='aspirant',
            name='name',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
