# Generated by Django 5.1.7 on 2025-06-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0007_remove_aspirant_learner_aspirant_grade_aspirant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirant',
            name='grade',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='aspirant',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
