# Generated by Django 5.1.7 on 2025-07-01 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0008_alter_aspirant_grade_alter_aspirant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='password',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
    ]
