# Generated by Django 5.1.7 on 2025-07-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0009_learner_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role_or_subject', models.CharField(max_length=100)),
                ('initials', models.CharField(editable=False, max_length=10, unique=True)),
                ('password', models.CharField(blank=True, editable=False, max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Staff',
            },
        ),
    ]
