# Generated by Django 5.1.7 on 2025-07-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0010_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='has_voted',
            field=models.BooleanField(default=False),
        ),
    ]
