# Generated by Django 5.1.7 on 2025-07-02 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0011_staff_has_voted'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='election.staff'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='learner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='election.learner'),
        ),
    ]
