# Generated by Django 5.1.7 on 2025-07-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0012_vote_staff_alter_vote_learner'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='title',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Aunty', 'Aunty'), ('Uncle', 'Uncle'), ('Sir', 'Sir')], default='Mr.', max_length=10),
        ),
        migrations.AlterField(
            model_name='vote',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
