# Generated by Django 5.1.7 on 2025-07-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0013_staff_title_alter_vote_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='title',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Aunty', 'Aunty'), ('Uncle', 'Uncle'), ('Sir', 'Sir')], max_length=10),
        ),
    ]
